export const API_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDBjRDMyQWNDOGY1MkE4ODk4NkI1ZTE4NDczQWEzMEEzQWVmMkQzQTMiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY5OTQzMzkyOTgyNCwibmFtZSI6InBvbHlnb24ifQ.d10705__soEzguh6Flz-m2q9xbpWvfbG11SMTSb23EQ";
export const ASSETSFOLDERPATH = "assets";
export const NFT_NAME = "NAME";
export const NFT_DESCRIPTION = "DESCRIPTION";
